server {
    server_name hotel.cvmaj.com;

    root /var/www/hotel.cvmaj.com;
    access_log /var/www/hotel.cvmaj.com/_access.log;
    error_log /var/www/hotel.cvmaj.com/_error.log error;

    index index.php;

    charset utf-8;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock; # sesuaikan
          
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hotel.cvmaj.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hotel.cvmaj.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = hotel.cvmaj.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name hotel.cvmaj.com;
    listen 80;
    return 404; # managed by Certbot


}